version: '3.8'

services:
  postgres:
    container_name: database
    image: postgres
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./database/createTables.sql:/docker-entrypoint-initdb.d/createTables.sql
